### ISSUE TITLE
Refactoring of the class ClassPathContentHandler 

### ISSUE THREAD

**Issue by Verdent** [oracle/helidon#256] opened 2018-12-13 14:11 UTC
Method doHandle in the class ClassPathContentHandler needs to be refactored. It uses java.nio.Path as path to content on classpath. When used on Windows it returns path with backward slash.

**Comment by m0mus** [comment] 2019-08-22 16:32
Duplicate of #298

**Closed by m0mus** 2019-08-22 16:32 UTC
Labels: SE, graal
