### ISSUE TITLE
Leak warning Helidon SE

### ISSUE THREAD

**Issue by tweenietomatoes** [oracle/helidon#2000] opened 2020-06-13 18:28 UTC
Helidon 2.0.0 RC1,
Helidon SE,
OpenJDK 11,
Ubuntu 18.04

Running an API with several routes. Using request predicate.

Jun 13, 2020 5:54:55 PM io.helidon.webserver.ByteBufRequestChunk logLeak
WARNING: LEAK: RequestChunk.release() was not called before it was garbage collected. While the Reactive WebServer is designed to automatically release all the RequestChunks, it still comes with a considerable performance penalty and a ...

**Comment by romain-grecourt** [comment] 2020-06-14 05:00
This message indicates that some chunks were not released.

How are you consuming the payload in your handlers ? Are you subscribing to the reactive publisher manually or are you using some media support of Helidon ?

**Comment by tweenietomatoes** [comment] 2020-06-14 13:58
I found that previously 2 person had that same issue in github closed issues but that person did not share how he resolved.

Also in micro cloud servers, server is freezing after a while due to high memory usage i believe. 

**I am using Jsonp support.**

`        
MediaSupport jsonpSupport = JsonpSupport.builder().build();
WebServer.builder(routing).port(8080)
.addMediaSupport(jsonpSupport)
.build().start();
`

**Also putting some values in context.**

`
HashMap user..
Contexts.context().ifPresent(it -> it.register("user", user));

 public HashMap<String, String> get(ServerRequest req) {

        Optional<HashMap> getUserContext = req.context().get("user", HashMap.class);

        HashMap<String, String> hashMap = new HashMap<String, String>();
        getUserContext.ifPresent(item -> {
            hashMap.putAll(item);
        });

        return hashMap;
    }
`

**Comment by tweenietomatoes** [comment] 2020-06-14 20:51
Also i am using .post, .get type of routes.

```
  .post("/station/status", RequestPredicate.create().and(Auth::isUserAuthenticated)
                        .thenApply(Handler.create(JsonObject.class, Station::statusHandler)))
```

I was also getting pgsql connection timeout in one of my routes after couple minutes, but it has to be handled by helidon isn't it? i'm returning an error response.

**Comment by romain-grecourt** [comment] 2020-06-16 02:34
If you are using `JsonpSupport` this could indicate a bug. Can you share a reproducer ?

**Comment by tweenietomatoes** [comment] 2020-06-16 21:57
my code is very similar to examples. nothing special.

`
 Routing routing = Routing.builder()
                .register(HealthSupport.builder().addLiveness(HealthChecks.healthChecks()).build())
                .register(MetricsSupport.create())
                .post("/user/login", Handler.create(JsonObject.class, User::userLoginHandler))
                .post("/user/register", Handler.create(JsonObject.class, User::userRegisterHandler))
               ...requestpredicate routes...
                .error(JsonParsingException.class, (req, res, err) -> { res.status(Http.Status.BAD_REQUEST_400).send(jsonBuilder.add("msg", "JSON Err").build()); })
                .error(JWTVerificationException.class, (req,res,err) -> { res.status(Http.Status.FORBIDDEN_403).send(jsonBuilder.add("msg", "Invalid auth." ).build()); })
                .error(PSQLException.class, (req, res, err) -> { res.status(Http.Status.INTERNAL_SERVER_ERROR_500).send(jsonBuilder.add("msg", "Internal Server Error. :(").build()); })
                .error(SocketTimeoutException.class, (req, res, err)-> {res.status(Http.Status.INTERNAL_SERVER_ERROR_500).send(jsonBuilder.add("msg","Timeout").build()); })
                .build();

       Config config = Config.create();
        WebServer server = WebServer.builder(routing).config(config.get("server"))
                .addMediaSupport(JsonpSupport.create())
                .build();

        server.start()
                .thenAccept(ws -> {
                    System.out.println(
                            "WEB server is up! :" + ws.port());
                    ws.whenShutdown().thenRun(()
                            -> System.out.println("WEB server is DOWN. Good bye!"));
                })
                .exceptionally(t -> {
                    System.err.println("Startup failed: " + t.getMessage());
                    t.printStackTrace(System.err);
                    return null;
                });
`

**Comment by tweenietomatoes** [comment] 2020-06-16 22:13
i get leak error in all cases with the usage above.

**Comment by romain-grecourt** [comment] 2020-06-16 22:44
I did a minimal server with a `POST` endpoint using jsonp:

```java
WebServer.builder(Routing.builder()
    .post("/", Handler.create(JsonStructure.class, (req, res, json) -> {
        System.out.println("OK");
        res.send("OK\n");
    }))
    .build())
    .port(8080)
    .addMediaSupport(JsonpSupport.create())
    .build()
    .start()
    .thenAccept(ws -> {
        System.out.println("WEB server is up! http://localhost:" + ws.port() + "/greet");
        ws.whenShutdown().thenRun(() -> System.out.println("WEB server is DOWN. Good bye!"));
    })
    .exceptionally(t -> {
        System.err.println("Startup failed: " + t.getMessage());
        t.printStackTrace(System.err);
        return null;
    });
}
```

Then I'm sending a 1MiB JSON file in a loop using curl:

```bash
while true ; do curl http://localhost:8080 -d @test.json ; sleep 1 ; done
```

And finally using visualvm to trigger GC.
Unfortunately I cannot reproduce with that, we need to nail the specifics of your use-case that triggers the leak error message.

**Comment by tweenietomatoes** [comment] 2020-06-17 01:47
i can't reproduce it easly either.
i made few changes and after that i can't reproduce it :( .

**Comment by tweenietomatoes** [comment] 2020-06-17 02:13
maybe it was happening with former jsonp support in m3.

**Comment by romain-grecourt** [comment] 2020-06-18 16:59
I'm going to close this issue for now. We will re-open if we need to track this issue again.

**Closed by romain-grecourt** 2020-06-18 16:59 UTC
Labels: 2.x, SE, bug, webserver
