### ISSUE TITLE
Rollback not working for SODA transactions

### ISSUE THREAD

**Issue by ddrechse** [oracle/helidon#4120] opened 2022-04-12 15:30 UTC
## Environment Details
* Helidon Version:  2.3.1 behaves as expected
                                2.4.0 and 2.5.0 are broken
* Helidon SE or Helidon MP
               MP
* JDK version:
           FROM openjdk:11-jre-slim
* OS:
           
* Docker version (if applicable):

----------

## Problem Description
Terminate an application in the middle of a SODA transaction and the insert is not rolled back even though the connection has autoCommit turned off

In 2.31, the code below works correctly.  The row is not inserted
in 2.4..0 and 2.5.0, it is broken.  Even though commit is not called, the table is updated

## Steps to reproduce
          OracleConnection jdbcConnection = null;
        try {
            jdbcConnection = (OracleConnection) dataSource.getConnection();
            System.out.println("SET AUTOCOMMIT TO FALSE");
            jdbcConnection.setAutoCommit(false);

            Order order = new Order(orderid, itemid, deliverylocation, "pending", "", "");
            OracleDatabase soda = new OracleRDBMSClient().getDatabase(jdbcConnection);
            OracleCollection col = soda.openCollection("orderscollection");
            if (col == null) {
                OracleDocument metaDoc = new OracleRDBMSClient().createMetadataBuilder().mediaTypeColumnName("CONTENT_TYPE").keyColumnAssignmentMethod("CLIENT").build();
                col = soda.admin().createCollection("orderscollection", metaDoc);
            }
            OracleDocument doc = soda.createDocumentFromString(order.getOrderid(), JsonUtils.writeValueAsString(order));
            col.insert(doc);

            if (OrderResource.crashAfterInsert) System.exit(-1);  // set to true to have process crash prior to commit

            jdbcConnection.commit();

**Comment by ljnelson** [comment] 2022-04-12 15:40
Are you running this code inside a method annotated with `@Transaction`?  (I'm not necessarily suggesting that you should, just trying to understand the problem.)

Which connection pool integration are you using: Hikari or Oracle's Universal Connection Pool?

**Comment by ddrechse** [comment] 2022-04-12 15:46
There are no annotations on the method that encapsulates above
There are annotations on the method calling that method

    @Path("/placeOrder")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Traced(operationName = "OrderResource.placeOrder")
    @Timed(name = "order_placeOrder_timed") //length of time of an object
    @Counted(name = "order_placeOrder_counted") //amount of invocations
    public Response placeOrder(
    
    
    
  These are the dependecies from pom
  
          <dependency>
            <groupId>com.oracle.database.soda</groupId>
            <artifactId>orajsoda</artifactId>
            <version>1.1.7.1</version>
            <exclusions>
                <exclusion>
                <groupId>com.oracle.database.jdbc</groupId>
                <artifactId>ojdbc8</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>

**Comment by ljnelson** [comment] 2022-04-12 15:50
If you are not, for example, using our JPA integration (it seems you are not), and you are not, as you say, using our JTA integration (no `@Transactional` annotation, so no Helidon magic here either), then unless I'm missing something else Helidon isn't even involved in this problem, right?  Still trying to understand your usage: maybe `dataSource` is something that Helidon supplies?  Could you describe how you acquire that?

**Comment by ljnelson** [comment] 2022-04-12 15:51
(To put all this another way: I should be able to write a unit test using just the connection and some insert statements, right?  Or do you think something else is going on?)

**Comment by ddrechse** [comment] 2022-04-12 17:48
Hi,

We have this
    @Inject
    @Named("orderpdb")
    PoolDataSource atpOrderPdb;
    
 And I there is a config file, microprofile-config.properties
 
 # DB properties (replaced by env values)
oracle.ucp.jdbc.PoolDataSource.orderpdb.URL = jdbc:oracle:thin:/@gdpaulob2o_tp?TNS_ADMIN=/Users/pparkins/Downloads/Wallet_gdpaulob2o
oracle.ucp.jdbc.PoolDataSource.orderpdb.user = orderuser
oracle.ucp.jdbc.PoolDataSource.orderpdb.password = password:
oracle.ucp.jdbc.PoolDataSource.orderpdb.connectionFactoryClassName = oracle.jdbc.pool.OracleDataSource
oracle.ucp.jdbc.PoolDataSource.orderpdb.inactiveConnectionTimeout = 60
 

hth

**Comment by ddrechse** [comment] 2022-04-12 17:49
idk, I did not try with standard SQL statements, the issue was found using SODA

**Comment by ddrechse** [comment] 2022-04-12 18:06
If I build with Helidon 2.3.1, It works as expected
If I build with Helidon 2.4.0, it doesn't
all things being equal

**Comment by ddrechse** [comment] 2022-04-12 18:07
If i write a simple Java client, it works as expected

**Comment by paulparkinson** [comment] 2022-04-12 18:08
Hey @ljnelson 😄   
@ddrechse Let's try to factor soda out and, as Laird more or less alludes to, look at what version of ucp is getting pulled in. Ie get rid of all com.oracle.database dependencies in the pom, leaving only helidon-integrations-cdi-datasource-ucp 
It may be some transient dependency thing by virtual of using different Helidon version.

**Comment by ddrechse** [comment] 2022-04-12 18:17
There nothing transient about it but I'll give it a go, so take all those references to oracle.database out of the POM?

**Comment by paulparkinson** [comment] 2022-04-12 18:23
Sorry, (spell-corrected wrongly I guess), I meant transitive and yes remove them as I believe helidon-integrations-cdi-datasource-ucp brings in a default set. 
Another thing you might try in order to isolation is creating the datasource from scratch (as you do in the standalone app) in helidon, rather than injecting it.
@ljnelson FYI https://github.com/oracle/microservices-datadriven/tree/main/grabdish/order-helidon is the reproducer in question.

**Comment by ljnelson** [comment] 2022-04-12 18:35
Thanks, @paulparkinson; I'll see if I can look at the reproducer later this week.

**Comment by ljnelson** [comment] 2022-04-12 18:42
Regarding the transitive dependencies of Helidon's UCP integration: I _seem_ to recall after some negotiation all stakeholders arrived at [supporting this use case](https://www.oracle.com/database/technologies/maven-central-guide.html#:~:text=Use%20Case%201%3A%20I%20Want%20the%20Production%20Jars) out of the box.  It may end up being a better decision to pare this down more in Helidon proper; not sure.

**Comment by paulparkinson** [comment] 2022-04-15 13:58
As suspected this is not specific to soda and is not directly a helidon issue (is transitive). I'll update you when we know more but you can close this as far as being a helidon bug.

**Comment by ljnelson** [comment] 2022-04-15 14:36
OK, sounds good. Please do comment on this (soon to be closed) issue because now you've got me curious!

**Closed by ljnelson** 2022-04-15 14:36 UTC
Labels: jpa/jta

**Comment by ddrechse** [comment] 2022-04-15 14:56
We have reproduced this issue outside of Helidon
Its a UCP data corruption bug in 21.x versions
Basically, 21.x versions of UCP are automatically committing on failure resulting in the committing an uncommitted (partial) transaction.
