### ISSUE TITLE
Incorrect parent span when  asyncResponse and  jersey client used together

### ISSUE THREAD

**Issue by crmouli** [oracle/helidon#1540] opened 2020-03-19 13:18 UTC
We have MP service with jaeger tracing enabled. It uses AsyncResponse to serve the get request and also invokes another rest endpoint using jersey client. Randomly noticed that some spans are being created under incorrect parent.

## Environment Details
* Helidon Version:1.4.1
* Helidon MP
* JDK version: 1.8
* OS:ubuntu
* Docker version (if applicable):

----------

## Problem Description
I noticed jax-rs client logging PUT request under a random span. We are using AsyncResponse and it looks like findParentSpan is using tracer.actvieSpan() which is returning a span which is already finished. 
helidon-tracing-jersey-client-1.4.1.jar!/io/helidon/tracing/jersey/client/ClientTracingFilter.class

## Steps to reproduce
1. Use helidon-mp service and implement a get service using asyncResponse
2. As part of this get service invoke another rest endpoint could be put or post using jersey client. 
3. while debugging noticed that findParentSpan is using tracer.actvieSpan() which is returning a span which is already finished. See code in this file.
helidon-tracing-jersey-client-1.4.1.jar!/io/helidon/tracing/jersey/client/ClientTracingFilter.class

Sorry, I find it difficult to provide stand alone test case as we are using oci ObjectStorageAsyncClient to connect to object store which internally uses jersey client.

**Comment by tomas-langer** [comment] 2020-04-16 09:12
The active span is used because of a requirement in an MP specification. We need to find a way to satisfy the MP spec and also make sure this works in asynchronous processing.

**Comment by tomas-langer** [comment] 2020-09-25 15:50
I am not able to replicate the behavior. I have created a test that runs multiple requests in parallel using asynchronous JAX-RS method and reactive JAX-RS client, and all the spans are correctly connected.
We have done some changes in the executor services for asynchronous JAX-RS processing, so maybe this was fixed as a side effect of those changes. 
There is also a chance I did not manage to do the right code to trigger this problem. I will add the test to our main code base. 
If you manage to reproduce, please let me know and I will try to create a test that does the same.

**Comment by tomas-langer** [comment] 2020-10-08 12:23
Closing this issue, as we are not able to reproduce. If this is still a problem, please describe the use case and I will try to reproduce and fix.

**Closed by tomas-langer** 2020-10-08 12:23 UTC
Labels: MP, P2, bug
