### ISSUE TITLE
CJK in URL causes error in webserver

### ISSUE THREAD

**Issue by iminto** [oracle/helidon#27] opened 2018-09-11 05:02 UTC
I request the follow url:
`curl -X GET http://localhost:8080/greet/小高
`
and then,log:
`2018.09.11 12:53:09 严重 io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-3,10,main]: Unexpected error occurred during routing!
java.lang.IllegalArgumentException: Illegal character in path at index 9: /greet/å°é«
        at java.net.URI.create(URI.java:852)
        at io.helidon.webserver.netty.BareRequestImpl.getUri(BareRequestImpl.java:81)
        at io.helidon.webserver.RequestRouting.createRequestSpan(RequestRouting.java:123)
        at io.helidon.webserver.RequestRouting.route(RequestRouting.java:69)
`

**Comment by barchetta** [comment] 2018-09-12 16:01
I've reproduced this. The webserver immediately closes the connect upon hitting the exception which results in an empty response to the client. This is clearly a bug. On an error the server should be returning the correct HTTP status (maybe 400 in this case? See next point).

The next question is if the URL is valid as represented in the HTTP request sent to the server. It appears as though `curl` is not encoding the URL. The webserver is assuming that incoming URLs  are correctly encoded (as defined by the HTTP protocol). In this case the URL in the HTTP request is not URL encoded (It is not `http://localhost:8080/greet/%E5%B0%8F%E9%AB%98`). And therefore the webserver gets the exception. 

If you try the same thing but use a browser to enter the URL it should work, because the browser encodes the URL. It worked for me with both Chrome and Firefox.

But we do need to fix the error handling in the webserver so that it handles the connection and returns an HTTP status code.

**Comment by barchetta** [comment] 2019-06-18 22:31
This is fixed by PR #796

**Closed by barchetta** 2019-06-18 22:31 UTC
Labels: bug, webserver
