### ISSUE TITLE
Static content doesn't work in native image

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#1954] opened 2020-06-09 18:18 UTC
## Environment Details
* Helidon Version: 2.0.0-RC1
* Helidon MP
* JDK version: GraalVM Version 20.0.1 EE
* OS: Ubuntu 18.04.4 LTS
----------

## Problem Description
After compilation to native image, static content stop working.
```
No handler found for path: /
```

## Steps to reproduce

1. `git clone https://github.com/danielkec/myproject.git`
2. `helidon build --mode NATIVE`
3. `cd target`
4. `./myartifactid`
5. http://localhost:7001/

**Comment by m0mus** [comment] 2020-06-11 16:50
Closing as duplicate of #1974 baby

**Closed by m0mus** 2020-06-11 16:50 UTC
Labels: MP, duplicate, native-image
