### ISSUE TITLE
Injected UriInfo provides wrong base URI in containerized environment

### ISSUE THREAD

**Issue by bfedoronchuk** [oracle/helidon#3272] opened 2021-08-14 11:35 UTC
## Environment Details
* OS: MacOS
* Docker version: 20.10.5 Community
* JDK version: 11
* MicroProfile implementation: Helidon MP
* Helidon Version: 2.3.2

----------

## Problem Description
Injected ```javax.ws.rs.core.UriInfo``` (via ```@Context``` annotation) provides the wrong base URI. It provides a local container IP address and port.

This issue was found during the implementation of redirection using JAX-RS utilities. The sample is provided below.

## Steps to reproduce

Steps to reproduce:
1. Setup Helidon MP example project.
```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion=2.3.2 \
    -DgroupId=io.helidon.examples \
    -DartifactId=wrong-uri-issue \
    -Dpackage=io.helidon.examples.quickstart.mp;
```
2. Add resource.
```
import javax.enterprise.context.RequestScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import java.net.URI;

@Path("/test")
@RequestScoped
public class TestRedirectResource {
    @Context
    private UriInfo uriInfo;

    @GET
    @Path("/redirect")
    public Response redirect() {
        URI forwardUri = uriInfo.getRequestUriBuilder().path("/hello").build();
        return Response.temporaryRedirect(forwardUri).build();
    }

    @GET
    @Path("/redirect/hello")
    public Response getGreeting() {
        return Response.ok("Hello!").build();
    }
}

```
3. Go to the project.
```
cd wrong-uri-issue;
```
4. Build Docker image.
``` 
docker build -t wrong-uri-issue . 
```
5. Run Docker container.
```
docker run --rm -p 9090:8080 wrong-uri-issue:latest
```
6. Open http://127.0.0.1:9090/test/redirect in the browser.
Browser redirects to the wrong path: http://172.17.0.2:8080/test/redirect/hello
Where 172.17.0.2 is the Docker container internal IP and 8080 is the port of the app running inside of the container.

## Problem details
As I found problem code is [here](https://github.com/oracle/helidon/blob/2.3.2/webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java#L195) in JerseySupport class. 
```
    private static URI baseUri(ServerRequest req) {
        try {
            return new URI(req.isSecure() ? "https" : "http", null, req.localAddress(),
                           req.localPort(), basePath(req.path()), null, null);
        } catch (URISyntaxException e) {
            throw new HttpException("Unable to parse request URL", Http.Status.BAD_REQUEST_400, e);
        }
    }
```
Helidon uses local address and port to instantiate URI which is part of injected UriInfo.

**Comment by romain-grecourt** [comment] 2021-08-17 18:30
This is not a bug. The server cannot know of the actual IP address used by the client, unless it looks at the HOST header.
You have the same problematic when fronting your application with a reverse proxy / load balancer.

Using an absolute URI in the redirection will expose the internal IP address of the server, you may want to use a relative URI instead.

Side note, MacOS does not have a direct route to the docker container's internal IP address so the redirect hangs. This would be different on Linux as you'd have a route to that IP address.

**Comment by spericas** [comment] 2021-08-17 19:10
As stated by @romain-grecourt, this is not a bug, but an architectural problem. URLs must be resolved by the client for this to work in modern applications behind reverse proxies, etc. If this is not your use case, you should consider using other Docker network types such as `host`.

**Closed by spericas** 2021-08-17 19:10 UTC
