### ISSUE TITLE
Exception on IntelliJ IDEA

### ISSUE THREAD

**Issue by longtran84** [oracle/helidon#631] opened 2019-04-30 13:47 UTC
2019.04.30 20:42:45 INFO org.jboss.weld.Version Thread[main,5,main]: WELD-000900: 3.0.3 (Final)
2019.04.30 20:42:45 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-000020: Using jandex for bean discovery
2019.04.30 20:42:45 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2019.04.30 20:42:45 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2019.04.30 20:42:45 WARN org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$JaxRsParamProducer is deprecated from CDI 1.1!
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.classfilewriter.ClassFile$1 (file:/home/longtran/.gradle/caches/modules-2/files-2.1/org.jboss.classfilewriter/jboss-classfilewriter/1.2.1.Final/a8d1e63cdc362229740637296db037d84d9c017e/jboss-classfilewriter-1.2.1.Final.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.classfilewriter.ClassFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019.04.30 20:42:46 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-002003: Weld SE container e2ae6fa4-8b52-4928-bf6d-6eff9f47aa1a initialized
2019.04.30 20:42:46 WARNING io.helidon.microprofile.server.Server$Builder Thread[main,5,main]: Failed to find JAX-RS resource to use
2019.04.30 20:42:46 INFO io.netty.util.internal.PlatformDependent Thread[main,5,main]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2019.04.30 20:42:46 INFO io.helidon.webserver.netty.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x1be06263, L:/0:0:0:0:0:0:0:0:8080]
2019.04.30 20:42:46 INFO io.helidon.microprofile.server.ServerImpl Thread[nioEventLoopGroup-2-1,10,main]: Server started on http://localhost:8080 (and all other host addresses) in 83 milliseconds.
http://localhost:8080/greet

**Comment by spericas** [comment] 2019-04-30 14:22
There are no exceptions here, only some WARNINGs. Does the application work?

**Comment by longtran84** [comment] 2019-04-30 14:45
2019.04.30 20:42:46 WARNING io.helidon.microprofile.server.Server$Builder Thread[main,5,main]: Failed to find JAX-RS resource to use -> so application not works

**Comment by spericas** [comment] 2019-04-30 14:52
Looks like a duplicate of #632 then. We can reopen this one later if different.

**Closed by spericas** 2019-04-30 14:52 UTC
Labels: duplicate
