### ISSUE TITLE
UriInfo#getBaseUri() returns URL with 1 character short

### ISSUE THREAD

**Issue by liquidblock** [oracle/helidon#1106] opened 2019-10-17 11:31 UTC
## Environment Details
* Helidon Version: 1.3.1
* Helidon MP
* JDK version: 1.8
* OS: Windows 10, Ubuntu 18.04 (WSL)

----------

## Problem Description
When using the ApplicationPath `/my/application/path` and the Path `/` for a Resource, then the UriInfo#getBaseUri() returns `http://127.0.0.1:8080/my/application/pat/` for the GET request `http://localhost:8080/my/application/path` (provided the server is running locally with port 8080).
I either expect the Server to return `http://127.0.0.1:8080/my/application/path/` or that the GET request of `http://localhost:8080/my/application/path` returns Error 404 and is instead reachable with `http://localhost:8080/my/application/path/`.

### Example Application and Resource
```Java
@ApplicationScoped
@ApplicationPath("/my/application/path")
public class TestApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return CollectionsHelper.setOf(TestResource.class);
    }
}

@Path("/")
@RequestScoped
public class TestResource {

    @Context
    UriInfo info;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String getRootBaseURL() {
        return info.getBaseUri().toASCIIString();
    }

    @Path("/test")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String getTestBaseURL() {
        return info.getBaseUri().toASCIIString();
    }
}
```
When starting this application with helidon the following requests give the following outputs:
```bash
$ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path
http://127.0.0.1:8080/my/application/pat/
Code:200
```
```bash
$ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path/

Code:404
```
```bash
$ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path/test
http://127.0.0.1:8080/my/application/path/
Code:200
```
```bash
$ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path/test/
http://127.0.0.1:8080/my/application/path/
Code:200
```

## Additional observations
- Why is TestResource#getTestBaseURL() available with the path `/my/application/path/test` and `/my/application/path/test/`, but TestResource#getRootBaseURL() is only available with the path `/my/application/path`?
- When setting @ApplicationPath("/my/application/path/") with a slash at the end, the application is neither available with `/my/application/path`, nor with `/my/application/path/`.
- for `http://localhost:8080/my/application/path` io.helidon.webserver.jersey.JerseySupport#basePath(ServerRequest req), has the following paths:
Breakpoint hit: "thread=helidon-1", io.helidon.webserver.jersey.JerseySupport.basePath(), line=185 bci=44 
helidon-1[1] print reqPath
 reqPath = "/"
helidon-1[1] print absPath
 absPath = "/my/application/path"
helidon-1[1] print basePath
 basePath = "/my/application/pat"

**Comment by spericas** [comment] 2019-10-18 15:13
The issue is easily reproducible and the crux of the problem is in the way `JerseySupport` computes base URIs. The fix is in #1106 and is a WIP as I review _all the observations_ raised in this issue.

For now I'll comment on the initial problem:

> ```shell
> $ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path
> http://127.0.0.1:8080/my/application/pat/
> Code:200
> ```

 Fixed by #1106.

> 
> ```shell
> $ curl -w '\nCode:%{http_code}\n' http://localhost:8080/my/application/path/
> 
> Code:404
> ```

 Fixed by #1106.

**Comment by spericas** [comment] 2019-10-18 15:56
> * Why is TestResource#getTestBaseURL() available with the path `/my/application/path/test` and `/my/application/path/test/`, but TestResource#getRootBaseURL() is only available with the path `/my/application/path`?

They are both available with the fix.

> * When setting @ApplicationPath("/my/application/path/") with a slash at the end, the application is neither available with `/my/application/path`, nor with `/my/application/path/`.

This is a different issue, a normalization step is missing for those paths.

**Comment by spericas** [comment] 2019-10-22 14:25
Issue(s) has been fixed.

**Closed by spericas** 2019-10-22 14:25 UTC
Labels: P1, bug
