### ISSUE TITLE
Helidon fails miserably if sending illegal characters in URI

### ISSUE THREAD

**Issue by pejomstd** [oracle/helidon#753] opened 2019-06-03 07:42 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.0.3
* Helidon SE 
* JDK version: 1.8
* OS: Windows
* Docker version (if applicable):

----------

## Problem Description
Helidon fails miserably if sending illegal characters in URI. 

There is nothing obvious to handle this programmatically, and I suspect hanging threads of non finished requests.

can easilly be reproduced by adding ?p=| to the request, e.x: http://localhost:8080/?p=|

`java.lang.IllegalArgumentException: Illegal character in path at index 3: /p=|
	at java.net.URI.create(URI.java:852)
	at io.helidon.webserver.BareRequestImpl.uri(BareRequestImpl.java:79)
	at io.helidon.webserver.RequestRouting.createRequestSpan(RequestRouting.java:131)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:69)
	at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:127)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 3: /p=|
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 25 more`

## Steps to reproduce
just call anything with ?p=| added

**Comment by barchetta** [comment] 2019-06-04 17:36
Possibly a duplicate of #27

**Comment by pejomstd** [comment] 2019-06-04 17:50
Not really a duplicate, it is one thing to allow characters, another to handle error due to hacking attempts, and having a way out of it.

**Comment by spericas** [comment] 2019-06-18 19:28
Fixed

**Closed by spericas** 2019-06-18 19:28 UTC
Labels: bug, webserver
