### ISSUE TITLE
BUG: CORS Config Path ordering is changed while processing CORS requests at times, causing CORS errors at random times.

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#4407] opened 2022-06-17 13:34 UTC
We have below CORS configuration entries in one of our applications, with the expectation that /authorize calls should match to first entry, /callback should match to second entry and all other calls to match to last default entry. I did not find any documentation that confirms the order of these entries are important - but we assumed the processing is based on the order.

Is this expectation correct? If not, then ignore the below points - and educate me on the options that we could use to achieve the above mentioned behaviour.

If the expectation is right, then we are noticing a different random ordering behaviour at times with Helidon MP. On debugging more, I noticed that, Aggregator::findFirst receives all entries from the below configuration as List and at times, the order or elements in this list is different from the order mentioned in the configuration. This creates an issue, as the Aggregator.findFirst method picks the first entry from the ones that match the pattern.

```yaml
 cors:
   paths:
     - path-pattern: "/authorize[/{+}]"
       allow-origins: ["*"]
       allow-methods: ["GET"]
       allow-credentials: true
     - path-pattern: "/callback[/{+}]"
       allow-origins: ["*"]
       allow-methods: ["PUT", "POST"]
       allow-credentials: true
     - path-pattern: "{^(?!((authorize)|(callback))).*$}"
       allow-origins: ["http://backend-base-uri}", "http://frontend-base-uri}", "http://test-origin}", "null"]
       allow-methods: ["DELETE", "PATCH", "HEAD"]
       allow-credentials: true
 ```

## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 17
* OS: Windows 11
* Docker version (if applicable): NA

**Comment by bvkrish83** [comment] 2022-06-21 06:44
Wanted to provide more details on this potential bug - I have noticed that the runtime ordering of the elements in the list is dependent on regex patterns in path-patterns.

Whatever be the case, Shouldn't the order of the elements be consistent with the order mentioned in the configuration? Else, it would result in runtime CORS failures - and that too randomly.

**Comment by tjquinno** [comment] 2022-06-23 14:13
@bvkrish83 As explained in the documentation https://helidon.io/docs/latest/index.html#/mp/cors/03_configuration-with-cors-mp#_understanding_the_mapped_cross_origin_configuration_format, the `path-pattern` values are _not_ regexes but _path patterns_ as used elsewhere in Helidon and described in the JavaDoc https://helidon.io/docs/latest/apidocs/io.helidon.webserver/io/helidon/webserver/PathMatcher.html  

It's not surprising to think they might be regexes which is actually why we chose the config key `path-pattern` instead of just `pattern` to help emphasize that. 

That said, our intent is that the path patterns be checked in the order they appear in the configuration. We will look into the potential ordering problem you mentioned. (The list is actually prepared well upstream from the `Aggregator#findFirst` method, based on the configuration, so any problem will be upstream from there as well.)

**Comment by tjquinno** [comment] 2022-06-23 14:26
In the environment details, you mentioned this is MP. 

We recommend (although obviously it's not required) that developers use `META-INF/microprofile-config.properties` to hold config in MP apps.

Although it's admittedly more cumbersome and wordy, using the `.properties` format might afford you a possible workaround. You'd convert the config to something like this:
```properties
cors.paths.0.path-pattern=/authorize[/{+}]
cors.paths.0.allow-origins=*
cors.paths.0.allow-methods=GET
cors.paths.0.allow-credentials=true
cors.paths.1.path-pattern=/callback[/{+}]
cors.paths.1...
```
etc.

Doing this _might_ make sure that the ordering is what you want. We'll need to verify that; depending exactly on what the problem is this might not work but if you have a chance please give that a try and see if it helps.

**Comment by tjquinno** [comment] 2022-06-23 17:47
No need to try the `.properties` format config. That will not help. Fix pending in 2.x and 3.x.

**Comment by tjquinno** [comment] 2022-06-23 23:12
2.x and 3.x PRs merged.

**Closed by tjquinno** 2022-06-23 23:12 UTC
Labels: bug, P2, 2.x, cors, 3.x
