### ISSUE TITLE
eclipselink cdi with helidon 2.0.1 and custom config not working

### ISSUE THREAD

**Issue by bhushan2901** [oracle/helidon#2115] opened 2020-07-01 16:46 UTC
## Environment Details
* Helidon Version: 2.0.1
*Helidon MP
* JDK version: 11
* OS: MAC
* Docker version (if applicable):

----------

## Problem Description
I am using ecpliselink cdi in our project when I upgraded from 1.4.4 to 2.0.1 it started throwing below error 

Internal Exception: org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type DataSource with qualifiers @Default @Named 

in my project I am using custom file configuration.  (all the configuration regarding DB i.e. javax.sql.DataSource.* is in config.properties) 

Config.builder().sources(file("conf/config.properties"),
				classpath("META-INF/microprofile-config.properties")).build();

When i moved javax.sql.DataSource.* properties to microprofile-config.properties it works fine. 

Is there anything I am doing wrong or is this regression ?
 I am following below documents for custom configuration. https://helidon.io/docs/v2/#/mp/guides/03_config#config/06_advanced-configuration.adoc 

and https://helidon.io/docs/v2/#/mp/guides/15_migration for migration. 

Thanks,
Bhushan.

**Comment by ljnelson** [comment] 2020-07-01 18:13
Hello; this problem doesn't have anything to do with Eclipselink, right?  Just `DataSource` configuration?

Secondly, I can't tell from the limited information here whether your `ConfigBuilder#build()` invocation is resulting in a `Config` that is then being used as the "main" MicroProfile Config `Config` instance.  Perhaps you could post more code or information?

**Comment by bhushan2901** [comment] 2020-07-01 19:58
yes this may not be problem with eclipselink actually not sure as i dont know the details about how config is being used in CDI. 

below is how i start the server :
                server = Server.builder().config(buildConfig()).build().start();
		System.out.println(config.getValue("javax.sql.DataSource.test.connectionFactoryClassName", String.class));
		System.out.println(config.getValue("javax.sql.DataSource.test.URL", String.class));
		System.out.println(config.getValue("javax.sql.DataSource.test.user", String.class));
		System.out.println(config.getValue("javax.sql.DataSource.test.password", String.class));


private static Config buildConfig() {
		return Config.builder().sources(file("conf/config.properties"),
				classpath("META-INF/microprofile-config.properties")).build();
	}

this dosent work but the console shows correct properties. 

whereas when  i add below system properties it works perfectly fine. 
		System.setProperty("javax.sql.DataSource.test.connectionFactoryClassName", "org.h2.jdbcx.JdbcDataSource");
		System.setProperty("javax.sql.DataSource.test.URL", "jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'src/test/resources/sql.init'");
		System.setProperty("javax.sql.DataSource.test.user", "sa");
		System.setProperty("javax.sql.DataSource.test.password", "");
                server = Server.builder().config(buildConfig()).build().start();

**Comment by ljnelson** [comment] 2020-07-02 03:42
One further question to help me out.  Could you see if your `Config` class—the one on which you're calling `.builder()`—is an instance of `org.eclipse.microprofile.config.Config`?

**Comment by bhushan2901** [comment] 2020-07-02 04:28
No , Config.builder().sources(file("conf/config.properties"),
classpath("META-INF/microprofile-config.properties")).build(); is io.helidon.config.Config

I also tried below.  with io.helidon.config.Config class. this did print correct values from property file but still got "Internal Exception: org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type DataSource with qualifiers " exception. 

private static Config buildConfig() {
return Config.builder().sources(file("conf/config.properties"),
classpath("META-INF/microprofile-config.properties")).build();
}
		Config cfg = buildConfig();
		System.out.println(cfg.get("javax.sql.DataSource.test.connectionFactoryClassName"));
		System.out.println(cfg.get("javax.sql.DataSource.test.URL"));
		System.out.println(cfg.get("javax.sql.DataSource.test.user"));
		System.out.println(cfg.get("javax.sql.DataSource.test.password"));
		s_server = Server.builder().config(cfg).build().start();

**Comment by ljnelson** [comment] 2020-07-02 17:09
I apologize; I am still confused by your comment.  It appears that you tried the same thing twice.  Could you please provide a reproducer?

Note that the JPA integration makes use of `org.eclipse.microprofile.config.ConfigProvider.getConfig()`.  We need to determine whether the `Config` you're supplying—whether it is a Helidon `Config` or a MicroProfile Config `Config`—is getting registered properly such that `org.eclipse.microprofile.config.ConfigProvider.getConfig()` will pick it up.

(Finally, the most portable (from a MicroProfile perspective) solution is not to use this programmatic setup at all, but to [write a `ConfigSourceProvider` following the MicroProfile Config documentation](https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/latest/org/eclipse/microprofile/config/spi/ConfigSourceProvider.html).  If one of these is found then the `ConfigSource`s it returns will be used and honored.)

**Comment by ljnelson** [comment] 2020-07-02 17:29
Notes to myself.

We are indeed turning a Helidon `Config` into a MicroProfile Config `Config`:

https://github.com/oracle/helidon/blob/e32e83adccaba93344c82fbf9ef2ee7081da36d9/microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java#L325-L332

…and we are indeed registering it:

https://github.com/oracle/helidon/blob/e32e83adccaba93344c82fbf9ef2ee7081da36d9/microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java#L206-L207

…so offhand I would think that a subsequent call to `ConfigProvider.getConfig()` should return this very `Config`:

https://github.com/oracle/helidon/blob/e32e83adccaba93344c82fbf9ef2ee7081da36d9/integrations/cdi/datasource/src/main/java/io/helidon/integrations/datasource/cdi/AbstractDataSourceExtension.java#L64

**Comment by bhushan2901** [comment] 2020-07-02 19:39
Hi @ljnelson sorry for confusion i just updated the comment https://github.com/oracle/helidon/issues/2115#issuecomment-652617479 

Also to confirm, using both org.eclipse.microprofile.config.Config and io.helidon.config.Config I am able to get the correct values.

**Comment by ljnelson** [comment] 2020-07-02 20:05
Assuming you're right, then, the problem will lie in [`MpConfigProviderResolver.java`](https://github.com/oracle/helidon/blob/master/config/config-mp/src/main/java/io/helidon/config/mp/MpConfigProviderResolver.java) and/or its interaction with [`org.eclipse.microprofile.config.ConfigProvider`](https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java).  It will take me quite some time to become familiar with the first class; kindly bear with me.

**Comment by ljnelson** [comment] 2020-07-22 20:34
(More notes to myself.)

This excerpt from an exploratory test case I'm writing emulates what's going on when you build the server in the way that you've described, and the JPA extension subsequently calls [`org.eclipse.microprofile.config.ConfigProvider.getConfig()`](https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/latest/org/eclipse/microprofile/config/ConfigProvider.html) to pick up the currently built/registered MicroProfile `Config` object as it should (the [specified way to get an `org.eclipse.microprofile.config.Config` object from within code somewhere if you're not injecting it](https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/latest/org/eclipse/microprofile/config/ConfigProvider.html)):

```
        assertThat(ConfigProviderResolver.instance(), sameInstance(ConfigProviderResolver.instance()));
        // This emulates what you're doing via Server.Builder.config(...) in your code above
        final org.eclipse.microprofile.config.Config mpConfig = ConfigProviderResolver.instance()
            .getBuilder()
            .withSources(MpConfigSources.create(Config.builder() // Helidon Config builder
                                                .sources(ConfigSources.file(Thread.currentThread()
                                                                            .getContextClassLoader()
                                                                            .getResource(this.getClass()
                                                                                         .getSimpleName()
                                                                                         + "/test.yaml")
                                                                            .getPath()))
                                                .build()))
            .build();
        final ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        ConfigProviderResolver.instance().registerConfig(mpConfig, classLoader);
        // This emulates what the JPA extension is doing
        final org.eclipse.microprofile.config.Config mpConfig2 = ConfigProvider.getConfig(classLoader);
        // My theory is that these two objects are not identical, but they should be
        assertThat(mpConfig, is(mpConfig2));
```
The final assertion fails (my assumption), suggesting that something about Helidon's implementation of `ConfigProviderResolver`'s `registerConfig(org.eclipse.microprofile.config.Config, ClassLoader)` method is not making that registered object available to `ConfigProvider`'s `static` `getConfig(ClassLoader)` method.  I need to confirm if this assumption codified in the assertion above is in fact required to be true of MicroProfile Config implementations (such as Helidon's).

**Comment by ljnelson** [comment] 2020-07-22 21:18
(More notes.)

While my assertion above naively should hold, there is apparently no explicit requirement that it do so.  Moving on to explore how these two different MicroProfile `Config` objects differ.  One is a delegate/wrapper object; the other is not, but both should behave the same and should contain the same information.

**Comment by ljnelson** [comment] 2020-07-22 21:43
Both objects do in fact return values from `test.yaml`, so so far this very isolated test does not reproduce the problematic behavior.

**Comment by ljnelson** [comment] 2020-07-22 22:19
Thinking now that perhaps this is at fault:

https://github.com/oracle/helidon/blob/32994ed45be94d3fae1bc22ac3aad0245c8daa13/integrations/cdi/datasource/src/main/java/io/helidon/integrations/datasource/cdi/AbstractDataSourceExtension.java#L57-L65

This may be too early for the Helidon MicroProfile Config implementation, i.e. depending on the order in which CDI decides to instantiate portable extensions this one might be instantiated before others that have a role in making the built `Config` object available to the `ConfigProvider`.  I need to be careful here since moving this may impact native image support (I am naïve in this area).

**Comment by ljnelson** [comment] 2020-07-22 22:42
Moving this later results in a `NullPointerException` in some file called `MetaConfigFinder.java`:
```
java.lang.NullPointerException
	at io.helidon.config.MetaConfigFinder.findClasspath(MetaConfigFinder.java:159)
	at io.helidon.config.MetaConfigFinder.lambda$findSource$5(MetaConfigFinder.java:115)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1601)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at io.helidon.config.MetaConfigFinder.findSource(MetaConfigFinder.java:117)
	at io.helidon.config.MetaConfigFinder.findMetaConfigSource(MetaConfigFinder.java:85)
	at io.helidon.config.MetaConfigFinder.findMetaConfig(MetaConfigFinder.java:55)
	at io.helidon.config.MetaConfig.metaConfig(MetaConfig.java:107)
	at io.helidon.config.mp.MpConfigProviderResolver.buildConfig(MpConfigProviderResolver.java:87)
	at io.helidon.config.mp.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:74)
	at io.helidon.config.mp.MpConfigProviderResolver.getConfig(MpConfigProviderResolver.java:54)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:91)
```
Still digging.

**Comment by ljnelson** [comment] 2020-07-23 01:13
I believe that at least some of root issues can be traced to something I'm seeing in #2207.  It in turn is indirectly related to [WELD-2494](https://issues.redhat.com/browse/WELD-2494).

**Comment by ljnelson** [comment] 2021-01-15 18:30
This should have been closed earlier; my apologies.  Please see #2207 for the root issue and #2269 for the resolution.

**Closed by ljnelson** 2021-01-15 18:30 UTC
Labels: P3, bug
