### ISSUE TITLE
Cannot read field "m_ucsChar" because "<local1>" is null

### ISSUE THREAD

**Issue by RojaRanganathan** [oracle/helidon#4848] opened 2022-09-07 17:55 UTC
## Environment Details

* Helidon Version:3.0.1
* Helidon MP
* JDK version: 17
* OS: Linux

----------

## Problem Description
I downloaded the latest helidon 3.0.1 Starter kit (pokemon app)from Helidon.io and modified the microprofile.properties to point to Oracle DB and running the app.

Consitently reproduced

```
2022.09.07 17:20:46 INFO org.hibernate.cfg.Environment Thread[main,5,main]: HHH000205: Loaded properties from resource hibernate.properties: {hibernate.bytecode.use_reflection_optimizer=false, hibernate.bytecode.provider=none}
2022.09.07 17:20:46 WARN org.hibernate.orm.deprecation Thread[main,5,main]: HHH90000021: Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead
Exception in thread "main" jakarta.enterprise.event.ObserverException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:296)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:340)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
	at io.helidon.microprofile.server.Main.main(Main.java:44)
Caused by: java.lang.ExceptionInInitializerError
	at oracle.jdbc.driver.T4CStatement.configureRowData(T4CStatement.java:563)
	at oracle.jdbc.driver.OracleStatement.initStatement(OracleStatement.java:946)
	at oracle.jdbc.driver.OracleStatement.<init>(OracleStatement.java:888)
	at oracle.jdbc.driver.T4CStatement.<init>(T4CStatement.java:1421)
	at oracle.jdbc.driver.T4CDriverExtension.allocateStatement(T4CDriverExtension.java:138)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:2131)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:2117)
	at oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:2083)
	at oracle.ucp.jdbc.oracle.OracleUniversalPooledConnection.getShardingMode(OracleUniversalPooledConnection.java:1102)
	at oracle.ucp.common.Topology.start(Topology.java:301)
	at oracle.ucp.common.Core.start(Core.java:2676)
	at oracle.ucp.common.UniversalConnectionPoolBase.start(UniversalConnectionPoolBase.java:739)
	at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.start(OracleJDBCConnectionPool.java:134)
	at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:797)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1834)
	at oracle.ucp.jdbc.PoolDataSourceImpl.access$300(PoolDataSourceImpl.java:223)
	at oracle.ucp.jdbc.PoolDataSourceImpl$3.build(PoolDataSourceImpl.java:3999)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1801)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1756)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1742)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at io.helidon.integrations.datasource.ucp.cdi.UniversalConnectionPoolAdapter$CommonDataSource$DataSource$ObjectFactory$PoolDataSource$Referenceable$Serializable$Wrapper$_$$_WeldClientProxy.getConnection(Unknown Source)
	at io.helidon.integrations.jta.jdbc.JtaDataSource.getConnection(JtaDataSource.java:572)
	at io.helidon.integrations.jta.jdbc.JtaDataSource.getConnection(JtaDataSource.java:393)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:284)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:177)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:36)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:255)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:230)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:44)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:217)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:190)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:138)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:142)
	at org.hibernate.jpa.HibernatePersistenceProvider$Proxy$_$$_WeldClientProxy.createContainerEntityManagerFactory(Unknown Source)
	at io.helidon.integrations.cdi.jpa.EntityManagerFactories.createContainerManagedEntityManagerFactory(EntityManagerFactories.java:189)
	at io.helidon.integrations.cdi.jpa.JpaExtension.lambda$addContainerManagedEntityManagerFactoryBeans$1(JpaExtension.java:1105)
	at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$CreateCallback.create(BeanConfiguratorImpl.java:368)
	at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$CreateCallback.access$700(BeanConfiguratorImpl.java:338)
	at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$ImmutableBean.create(BeanConfiguratorImpl.java:503)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
	at io.helidon.integrations.cdi.jpa.EntityManagerFactory$_$$_WeldClientProxy.isOpen(Unknown Source)
	at io.helidon.integrations.cdi.jpa.JpaExtension.onStartup(JpaExtension.java:2176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	... 16 more
Caused by: java.lang.NullPointerException: Cannot read field "m_ucsChar" because "<local1>" is null
	at oracle.jdbc.driver.DynamicByteArray$1.run(DynamicByteArray.java:961)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at oracle.jdbc.driver.DynamicByteArray.<clinit>(DynamicByteArray.java:956)
	... 78 more
```

## Steps to reproduce

- Login to helidon.io
- download the starter Pokemon app.
-  I tried all 4 combinations: UCP/Hikari/Eclipselink/Hibernate/, I see the same error.
- The server does not start throwing the above exception

Pokemon app, the only change I made is in the microprofile-config.properties to connect to Oracle DB.

**Comment by romain-grecourt** [comment] 2022-09-07 18:46
I'm assuming you've download an app from the starter page. I.e. https://helidon.io/starter

Can you please provide the complete set of options you've used to download the application. You can copy the URL from the browser address bar.

Can you also share the changes you've made to microprofile-config.properties, replace the confidential parts (ip / credentials) with placeholders.

**Comment by romain-grecourt** [comment] 2022-09-07 21:14
duplicate of https://github.com/oracle/helidon/issues/4738

**Closed by romain-grecourt** 2022-09-07 21:14 UTC

**Comment by RojaRanganathan** [comment] 2022-09-07 22:21
> I'm assuming you've downloadd an app from the starter page. I.e. https://helidon.io/starter
><Roja>  Correct
> Can you please provide the complete set of options you've used to download the application. You can copy the URL from the browser address bar.
><Roja>https://helidon.io/starter/3.0.1?flavor=mp&step=5&app-type=database&db.cp=ucp&db.server=oracledb&groupId=myGroupId&artifactId=myArtifactId&package=some.package.example

> Can you also share the changes you've made to microprofile-config.properties, replace the confidential parts (ip / credentials) with placeholders.
The only change I did was to populate my DB details in microprofile config properties
oracle.ucp.jdbc.PoolDataSource.ds1.url=jdbc:oracle:thin:@mymachine:myport/myservicename
oracle.ucp.jdbc.PoolDataSource.ds1.connectionFactoryClassName=oracle.jdbc.pool.OracleDataSource
oracle.ucp.jdbc.PoolDataSource.ds1.user=myuserid
oracle.ucp.jdbc.PoolDataSource.ds1.password=mypassword

**Comment by RojaRanganathan** [comment] 2022-09-07 22:25
> (This is due to [deserialization filtering](https://helidon.io/docs/v3/apidocs/io.helidon.common/io/helidon/common/SerializationConfig.html). The default behavior [was changed in Helidon 3](https://github.com/oracle/helidon/issues/3200). See also #4646 and #4738.)

yes, this seems like it. Per this article, I added the the property pattern=oracle.sql.converter.* in a new file METAINF/helidon/serial-config.properties file, that resolved the issue for now. thank you for pointing to the workaround

**Comment by RojaRanganathan** [comment] 2022-09-07 22:25
> duplicate of #4738

yes that fixed it. thank you :)
