### ISSUE TITLE
SocketException caught in ForwardingHandler for all requests

### ISSUE THREAD

**Issue by kofoeddk** [oracle/helidon#3916] opened 2022-02-24 13:53 UTC
## Environment Details

* Helidon MP Version: 2.4.2
* JDK version: 17
* Docker base image: registry.access.redhat.com/ubi8/openjdk-17:latest
* Runtime: Kubernetes v1.22.3+e790d7f
* OS: NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"

----------

## Problem Description

Since [this pull request](https://github.com/oracle/helidon/pull/3792/files) we're seeing one of the exceptions below per request. They occur almost exactly 15 seconds after returning any entity in a response. 
```
2022.02.23 08:24:18 SEVERE io.helidon.webserver.ForwardingHandler Thread[nioEventLoopGroup-3-1,10,main]: Error intercepted before request context established.
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I believe that the exception has probably always been there, but was just swallowed. Since PR 3792 this is obviously no longer the case.  

I also believe that it is somehow related to the underlying network, AND depends on specific environment settings, as I cannot reproduce it locally -- also when my app is built on the same docker image that is deployed to Kubernetes.

## Steps to reproduce

1. Build demo app with simple API returning any entity
2. Deploy to Kubernetes
3. Fire request for resource
4. Wait 15 seconds and check log output

**Comment by spericas** [comment] 2022-02-24 14:10
PR #3924 is already merged for this one

**Comment by m0mus** [comment] 2022-02-24 17:29
Duplicate of https://github.com/oracle/helidon/issues/3902

**Closed by m0mus** 2022-02-24 17:29 UTC
Labels: bug, P2
