### ISSUE TITLE
mvn checkstyle:checkstyle-aggregate fails in certain situations

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#778] opened 2019-06-13 02:50 UTC
To reproduce the problem, do the following:
1. Check out the `master` branch of Helidon and `cd` to its root.
2. `rm -rf ~/.m2/repository/io/helidon # ensure your cache is empty of Helidon artifacts`
3. `mvn checkstyle:checkstyle-aggregate -pl config/config -am`

You should get messages including something like the following (in my case I have a local [Nexus repository](https://www.sonatype.com/nexus-repository-oss) running; hence all the `localhost:8081` references below):

```
[INFO] ------------------< io.helidon.config:helidon-config >------------------
[INFO] Building Helidon Config 1.1.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common/1.1.2-SNAPSHOT/maven-metadata.xml
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common/1.1.2-SNAPSHOT/helidon-common-1.1.2-SNAPSHOT.pom
[WARNING] The POM for io.helidon.common:helidon-common:jar:1.1.2-SNAPSHOT is missing, no dependency information available
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common-reactive/1.1.2-SNAPSHOT/maven-metadata.xml
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common-reactive/1.1.2-SNAPSHOT/helidon-common-reactive-1.1.2-SNAPSHOT.pom
[WARNING] The POM for io.helidon.common:helidon-common-reactive:jar:1.1.2-SNAPSHOT is missing, no dependency information available
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/config/helidon-config-test-infrastructure/1.1.2-SNAPSHOT/maven-metadata.xml
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/config/helidon-config-test-infrastructure/1.1.2-SNAPSHOT/helidon-config-test-infrastructure-1.1.2-SNAPSHOT.pom
[WARNING] The POM for io.helidon.config:helidon-config-test-infrastructure:jar:1.1.2-SNAPSHOT is missing, no dependency information available
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common/1.1.2-SNAPSHOT/helidon-common-1.1.2-SNAPSHOT.jar
Downloading from nexus: http://localhost:8081/repository/maven-public/io/helidon/common/helidon-common-reactive/1.1.2-SNAPSHOT/helidon-common-reactive-1.1.2-SNAPSHOT.jar
```

(The `-pl` option to Maven tells it exactly what submodules to build (`config/config` in this case, near the very top of the dependency graph, and the first module in the dependency graph I could find that triggers this problem) and the `-am` option tells Maven to "also make" whatever is required to build the stuff mentioned in the `-pl` option.)

It is not immediately clear to me whether this is a fundamental problem with the `config/config` `pom.xml` or something similar, or a problem with the Checkstyle goal in question, or a general problem with running an aggregate-style goal before the `package` phase has completed.

**Comment by ljnelson** [comment] 2019-06-13 05:04
I should mention for completeness: the reason I'm filing the issue is not due to any problems with the Checkstyle goal or Helidon _per se_ but because an invocation like the kind I excerpted above gates PRs to this repository.

**Comment by barchetta** [comment] 2019-06-18 22:35
This was caused by a missing repository stanza in a pom in the PR. After that was fixed the checkstyle goal passed reliably. Closing.

**Closed by barchetta** 2019-06-18 22:35 UTC
Labels: build
