### ISSUE TITLE
Profile based configuration support for microprofile-config.properties

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1370] opened 2020-02-07 11:55 UTC
I am not be able to find any detailed documentation on profile based microprofile-config.properties support with Helidon. My requirement is to have different profile support based on my deployment stages like dev, test and prod.

Do we have any support for various deployment configuration passed during runtime? Either starting the server or set during boot? (-Dfile=xxx)

Can you give me some pointer? Might be a gap in the documentation

**Comment by m0mus** [comment] 2020-05-14 17:01
Duplicate of #1416

**Comment by tomas-langer** [comment] 2021-06-15 16:15
Duplicate of https://github.com/oracle/helidon/issues/3093
Support for configuration profiles in Helidon MP has been merged.
This will work according to MP specification (part of MP Config 2.0).

- support for profile specific files (`microprofile-config-dev.properties`)
- support for profile specific properties (`%dev-app.greeting=Hello Dev`)

Closing this issue as support is merged and will be part of 2.3.1

**Closed by tomas-langer** 2021-06-15 16:15 UTC
Labels: 2.x, P3, enhancement
