### ISSUE TITLE
1.4: Intermittent test hang: io.helidon.webserver.TestHttpParsingDefaults

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2248] opened 2020-08-11 23:20 UTC
Just had a pipeline job hang on:

```
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in io.helidon.webserver.HashResponseHeadersTest
Running io.helidon.webserver.TestHttpParsingDefaults
```
This seems intermittent since other times the pipeline has passed. Hung job was at: https://builds.helidon.io/53F3E72BE46274A8B665498126A9E580

Looks like this test was added by #2244

**Comment by romain-grecourt** [comment] 2020-08-21 02:24
Looks like this issue is still occurring: https://builds.helidon.io/0BD243C1F1146E2A381220C79A909663

**Comment by tomas-langer** [comment] 2020-08-31 16:24
@romain-grecourt any idea how to 
- increase the chance for this to happen
- get more information on running tests, such as which method is being executed? 

Even if I reproduce it (such as in the linked problem), I just see it was a specific class, I cannot see which test was the cause of the problem...

**Comment by tomas-langer** [comment] 2020-08-31 19:31
Failed to reproduce (300000 repeats of tests).

I will update the tests to have all the possible timeouts, so at least we find out which specific method is causing the failure

**Comment by tomas-langer** [comment] 2020-09-17 20:46
Closing this issue again. If this ever occurs again, please update and reopen.

**Closed by tomas-langer** 2020-09-17 20:46 UTC
Labels: 1.x, P1, bug, webserver
