### ISSUE TITLE
Browser access Helidon SE quickstart has an exception

### ISSUE THREAD

**Issue by biezhi** [oracle/helidon#30] opened 2018-09-12 01:47 UTC
I tried to build a Helidon SE program using maven. After starting the program, I used curl to access it without any problem. When I used the browser to access it, I got the following error:

```java
» java -jar target/quickstart-se.jar
[DEBUG] (main) Using Console logging
2018.09.12 09:40:01 信息 io.netty.util.internal.PlatformDependent Thread[main,5,main]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018.09.12 09:40:01 信息 io.helidon.webserver.netty.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x1be1a7d7, L:/0:0:0:0:0:0:0:0:8080]
WEB server is up! http://localhost:8080
2018.09.12 09:40:19 警告 io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-3,10,main]: Default error handler: Response wasn't successfully sent.
java.util.concurrent.CompletionException: io.helidon.webserver.SocketClosedException: Response channel is closed!
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.helidon.webserver.netty.BareResponseImpl.lambda$new$2(BareResponseImpl.java:104)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:764)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:740)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:945)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1376)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.helidon.webserver.netty.BareResponseImpl.lambda$completeInternal$9(BareResponseImpl.java:184)
	at io.helidon.webserver.netty.BareResponseImpl.runOnOutboundEventLoopThread(BareResponseImpl.java:308)
	at io.helidon.webserver.netty.BareResponseImpl.completeInternal(BareResponseImpl.java:172)
	at io.helidon.webserver.netty.BareResponseImpl.onComplete(BareResponseImpl.java:322)
	at io.helidon.webserver.SendHeadersFirstPublisher$DelegatingSubscriber.onComplete(SendHeadersFirstPublisher.java:131)
	at io.helidon.common.reactive.ReactiveStreamsAdapter$ReactiveStreamsSubscriber.onComplete(ReactiveStreamsAdapter.java:135)
	at reactor.core.publisher.Operators.complete(Operators.java:125)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at io.helidon.common.reactive.ReactiveStreamsAdapter$FlowPublisher.subscribe(ReactiveStreamsAdapter.java:104)
	at io.helidon.webserver.SendHeadersFirstPublisher.subscribe(SendHeadersFirstPublisher.java:77)
	at io.helidon.webserver.Response.lambda$send$5(Response.java:229)
	at io.helidon.webserver.Response$SendLockSupport.execute(Response.java:371)
	at io.helidon.webserver.Response$SendLockSupport.access$100(Response.java:358)
	at io.helidon.webserver.Response.send(Response.java:226)
	at io.helidon.webserver.Response.send(Response.java:240)
	at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:405)
	at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:382)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:330)
	at io.helidon.webserver.json.JsonSupport.accept(JsonSupport.java:156)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:337)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:103)
	at io.helidon.webserver.netty.ForwardingHandler.channelRead0(ForwardingHandler.java:119)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.helidon.webserver.SocketClosedException: Response channel is closed!
	at io.helidon.webserver.netty.BareResponseImpl.lambda$new$2(BareResponseImpl.java:103)
	... 66 more
```

The problem doesn't seem to come back when I try again, and I think helidon might have some hidden bugs.

**Comment by spericas** [comment] 2018-09-12 15:16
I'm not able to reproduce the problem using Chrome. Can you provide more information about your environment? Do you have a way to capture the browser's request? In Chrome, you could use the developer tools for that.

**Comment by biezhi** [comment] 2018-09-13 02:07
@spericas This situation only appears once, which may be difficult to reproduce. If I find that I will reply to this issue again, you can close this issue.

**Comment by spericas** [comment] 2018-09-13 13:03
Ok, I'm closing it. Please re-open with a reproducible test.

**Closed by spericas** 2018-09-13 13:03 UTC
Labels: question
