### ISSUE TITLE
Static content handling in native image does not use welcome file

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1974] opened 2020-06-10 19:09 UTC
## Environment Details
* Helidon Version: 2 RC1
* Helidon MP
* JDK version: native image 11
* OS: Mac and Linux

----------

## Problem Description
Routing on root uses both Jersey and Static content
There is a file `index.html` in the root of static content directory on classpath.

When run from hotspot, the `http://localhost:8080` returns the index.html
When run in native-image, the URL returns "no handler found for `/`"

It seems the classloader.getResource() for a directory returns `null` in native, while it returns a valid `URL` in hotspot.

We should be able to fix this by moving code from lines 106-108 to line 127 in `io.helidon.webserver.ClassPathContentHandler`, to make sure that the welcome file is not present (as the url for directory is not really useful).

**Comment by danielkec** [comment] 2020-06-11 08:42
Seems like duplicate of #1954

**Closed** 2020-06-12 08:15 UTC
Labels: MP, bug, native-image
