### ISSUE TITLE
Intermittent test failures in Kafka integration

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1735] opened 2020-05-06 11:43 UTC
Branch `master`
`KafkaCdiExtensionTest` fails on line 468 with timeout - as the timeout is configured to 30 seconds, this is most likely a race condition or a bug.
See https://builds.helidon.io/51A9EA2726241E0093DFA5D5139F3E6B/logs/14

**Comment by danielkec** [comment] 2020-05-11 12:05
Confirmed [flaky-kafka-test.log](https://github.com/oracle/helidon/files/4609403/flaky-kafka-test.log)

**Comment by jbescos** [comment] 2020-05-11 12:14
I missed this, I can take it.

**Comment by jbescos** [comment] 2020-05-11 15:00
I am not able to reproduce this locally in my computer after 40 tries.

I don't think there is a race condition, before every test we wait that the KafkaConsumer has the partitions assigned. This is done in the @BeforeEach after the comment 'Wait till consumers are ready'. Only after that, we produce new events, so consumers should be ready to consume them.

It could be a bug, but I should be able to reproduce it after so many tries.

Other possibility:

In the attached file of Daniel we can see that there are many events after the line '==========> test error()' related to the test someEventsNoAckWithOnePartition().

That is because in the test someEventsNoAckWithOnePartition() some events are not committed, so every new test execution after that is reading that events again and again, overloading a bit.

Correct me if I'm wrong but this tool we have for building is twice slow than the previous one we had. Maybe it is because of that.

For the time being I will decrease the number of events in the test so we can verify if this theory is correct or not.

**Comment by danielkec** [comment] 2020-06-25 16:55
Fixed by #1918

**Closed by danielkec** 2020-06-25 16:55 UTC
Labels: MP, P1, bug
