### ISSUE TITLE
ConfigProperty injection does not work on resource methods

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#548] opened 2019-04-04 09:58 UTC
When a resource method is annotated with ConfigProperty, the injected value is an empty String instead of the configuration value.

## Environment Details
* Helidon Version: 1.0.2
* Helidon MP

**Comment by m0mus** [comment] 2019-04-15 19:31
Validate that it's not required by the MP Config spec. If not it should be closed.

**Comment by batsatt** [comment] 2019-04-23 16:19
@tomas-langer Do you mean something like this?
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Inject
    public Response list(@ConfigProperty(name="max.results") int maxResults) {}
```
If so, Jersey does not understand this as you intend, seeing the parameter as an entity instead.

**Comment by m0mus** [comment] 2019-04-25 16:41
Closing as not a bug. This behavior is correct.

**Closed by m0mus** 2019-04-25 16:41 UTC
Labels: MP, bug, config, works as designed
