### ISSUE TITLE
Headers are not propagated from http request in JAX-RS to Microprofile rest client request

### ISSUE THREAD

**Issue by nix222** [oracle/helidon#2149] opened 2020-07-10 09:39 UTC
We are using Helidon MP 1.4.4 with a JAX-RS application that is making a request to a third-party API via Microprofile rest client. We want to propagate a header from a request made to JAX-RS resource to Microprofile rest client as described in MP documentation https://download.eclipse.org/microprofile/microprofile-rest-client-1.3/microprofile-rest-client-1.3.html#_jax_rs. We were not able to set up a working solution with the recommendations stated in the docs.

## Environment Details

* Helidon Version: 1.4.4
* Helidon MP
* JDK version: openjdk 11.0.2
* OS: macOS 10.13.6

## Problem Description

According to MP documentation when `@RegisterClientHeaders(CustomClientHeadersFactory.class)` annotation is added to
 MP rest client interface, the incoming HTTP headers are then available in `CustomClientHeadersFactory.update` method as its first parameter. Then those headers can be propagated to the request of the rest client. We faced a problem
   when we make an HTTP request with headers, rest client gets invoked, the `CustomClientHeadersFactory.update` method gets called but the first argument of this method where the headers should be is empty.

### Add implementation of `ClientHeadersFactory`

```
public class CustomClientHeadersFactory implements ClientHeadersFactory {

    @Override
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders,
                                                 MultivaluedMap<String, String> clientOutgoingHeaders) {
        System.out.println("--- Incoming headers of the JAX-RS environment");
        System.out.println("Headers size: " + incomingHeaders.size());

        MultivaluedMap<String, String> resultHeaders = new MultivaluedHashMap<>();
        resultHeaders.putAll(clientOutgoingHeaders);
        resultHeaders.putAll(incomingHeaders);

        return resultHeaders;
    }
}
```

### Define MP rest client interface

```
@RegisterRestClient
@RegisterClientHeaders(CustomClientHeadersFactory.class)
public interface ApiRestClient {

    @Path("/mocked-api/v1/data")
    @GET
    JsonArray requestApiData(@QueryParam("objectId") String objectId);
}
```

### Inject the rest client in JAX-RS service class

```
@Path("/v1")
@ApplicationScoped
public class HttpEndpointService {

    @Inject
    @RestClient
    private ApiRestClient restClient;

    @POST
    @Path("/test")
    @Produces(MediaType.TEXT_HTML)
    @Consumes(MediaType.APPLICATION_JSON)
    public Response requestHandler(JsonObject jsonObject) {

        restClient.requestApiData("test");

        return Response.ok("")
                .build();
    }
}
```

### Send a http request

```
curl --request POST \
  --url http://host:port/v1/test \
  --header 'content-type: application/json' \
  --header 'custom-header-to-propagate: propagate-me' \
  --data '{}'
```

### Current vs expected behavior

Now the server stdout contains the following lines
```
--- Incoming headers of the JAX-RS environment
Headers size: 0
```

The expected value is
```
--- Incoming headers of the JAX-RS environment
Headers size: 2
```

**Comment by Verdent** [comment] 2020-08-06 11:09
Hello @nix222 ,
I took a look into this issue and I have to say, that I was not able to reproduce it. Could you please provide a reproducer app?

**Comment by lennart-schulte** [comment] 2020-08-17 13:56
im having the same issue.. it works for you with above code snippets?

**Comment by lennart-schulte** [comment] 2020-08-19 08:06
can now confirm that it works if i build above into the MP demo app https://helidon.io/docs/latest/#/mp/guides/02_quickstart
so im wondering what my real app is doing that it doesnt work, will investigate

**Comment by lennart-schulte** [comment] 2020-08-19 10:11
my app is using threads in which then the rest client requests are made. headers are not available in this case (Headers size: 0)

e.g. with above code and the MP demo app, changing `getDefaultMessage()`
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject getDefaultMessage() {
        CompletableFuture<String> cf = CompletableFuture.supplyAsync( () -> restClient.requestApiData("test") );
        String res = cf.join();
        System.out.println(res);

        return createResponse("World");
    }
```

is this intended? and if yes, how would I be able to work around this?

**Comment by Verdent** [comment] 2020-09-08 09:22
Hi @lennart-schulte , I took a look into your code and the problem is in usage of `CompletableFuture.supplyAsync` since the rest client request is made in the different thread then the inbound request to the endpoint. Because of that the rest client does not see received inbound headers. 

If you need to execute async rest client call, you can change the return type of the executed method to be CompletionStage<T>. For example:
Instead of
```java
@GET
public String methodName();
```
Use this
```java
@GET
public CompletionStage<String> methodName();
```
This way your headers will be propagated.

**Comment by lennart-schulte** [comment] 2020-09-09 13:35
thanks a lot for your help! i'll try that 👍

**Comment by Verdent** [comment] 2020-10-12 08:20
I could not reproduce the original bug and fixed second reproducer. Closing as this is not a bug.

**Closed by Verdent** 2020-10-12 08:20 UTC
Labels: MP, P1, bug, jax-rs, rest-client
