### ISSUE TITLE
Allow propagation of Netty exceptions to Jersey/MP layer

### ISSUE THREAD

**Issue by aivarhe** [oracle/helidon#2501] opened 2020-11-04 19:10 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.0.1
* Helidon MP
* JDK version: 11.0.7
* OS: Windows 10
* Docker version (if applicable):

----------

## Problem Description
We have noticed that Helidon is internally handling the exceptions thrown by Netty in cases where Helidon is trying to send the response back to the client but the connection is already closed. The stack trace below shows an example of this scenario.

2020-11-02T13:33:43.904Z io.helidon.webserver.BareResponseImpl FINER 17652 Thread[nioEventLoopGroup-3-2,10,main] (reqID: 3) Response completion failed! java.lang.IllegalStateException: An exception occurred when writing headers. 
    at io.helidon.webserver.BareResponseImpl.lambda$completeOnFailureListener$7(BareResponseImpl.java:264) 
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) 
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) 
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) 
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) 
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) 
    at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993) 
    at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865) 
    at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707) 
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) 
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) 
    at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1087) 
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) 
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) 
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
    at java.base/java.lang.Thread.run(Thread.java:834) 
 Caused by: java.nio.channels.ClosedChannelException 
    at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957) 
    ... 15 more

Since the exceptions are not being propagated to the Jersey/MP layer, the application running in Helidon has no way of knowing that such exception occurred. Allowing the propagation of these type of exceptions to the Jersey/MP layer would allow applications to react to such events and perform any action needed to compensate (e.g. reverting an action performed during the processing of the request)

## Steps to reproduce
1. In Helidon MP, create a Jersey resource with a simple GET method that returns an string after 30 seconds (e.g. using Thread.sleep)
2. Configure a the client (e.g. Postman or curl) calling this Jersey resource, to timeout after 10 seconds
3. Using the client, send the request to the the resource
4. After 30 seconds, inspect the Helidon logs (logging needs to be set to FINER level in Helidon)

**Comment by spericas** [comment] 2020-11-09 15:36
@aivarhe Let's try the following, the outcome may be different depending on the OS. You can inject the underlying response object in MP as follows:

```
@Context 
private ServerResponse response;
```
And then in the resource method (it may not be available in the constructor) in question, you can register a completion handler:
```
@GET 
public Foo get() {
    response.whenSent().whenComplete((r, t) -> {
         System.out.println("### r " + r);
         System.out.println("### t " + t);
    });
   // process request
   // return result
}
```
The completion handler that you register should be called when the response is returned. The `r` represents the response and the `t` a throwable. 

If it easy for you try, I'd be interested in the outcome in your environment when a client disconnects prematurely.

**Comment by spericas** [comment] 2020-11-09 19:49
For what is worth, I cannot get the exception shown above. The behavior I'm seeing is similar to what is described here https://stackoverflow.com/questions/46169033/how-does-netty-server-know-when-client-is-disconnected

**Comment by spericas** [comment] 2020-11-10 14:25
@aivarhe After further tweaks, I was able to reproduce the exception that you reported in Netty. Unfortunately, it appears getting the exception depends on how much data is written to the broken connection: from my testing, a few bytes will not result in the exception being logged nor the handler shown above called with a non-null throwable.

The approach of injecting a `ServerResponse` and registering a completion handler may work for your use case, but it is in general an unreliable mechanism due to how Netty reports these exceptions. You may try it out and see if it works, but you should consider an application-layer mechanism to ensure atomicity that is more robust than the detection of broken client connections.

To conclude, given the ability to inject `ServerResponse` as described above, I don't believe there's any immediate need to add additional support for this in Helidon.

**Comment by spericas** [comment] 2020-11-19 18:03
@aivarhe Any update on this?

**Comment by aivarhe** [comment] 2020-11-19 19:25
I registered the completion handler in our application and I can see that when client disconnects prematurely, the throwable object in the handler is in fact the  io.helidon.webserver.SocketClosedException. 

Completion handler:
`response.whenSent().whenComplete((r, t) -> {
	         System.out.println("Response : " + r);
	         System.out.println("Exception: " + t);
	    });`

Log entries:
`Response : null
`
`Exception: java.util.concurrent.CompletionException: io.helidon.webserver.SocketClosedException: Response channel is closed!`

**Comment by spericas** [comment] 2020-11-19 20:07
@aivarhe OK, great. I will close this for now then. Keep in mind that relying on that call may not be the most robust way to handle transactions.

**Closed by spericas** 2020-11-19 20:07 UTC
Labels: P3, jax-rs, webserver
