### ISSUE TITLE
WebClient Proxy not getting set from environment variables

### ISSUE THREAD

**Issue by georgyrajan** [oracle/helidon#4427] opened 2022-06-23 12:39 UTC
## Environment Details
* Helidon Version:2.5
* Helidon SE or Helidon MP: MP
* JDK version:11
* OS: oraclelinux8
* Docker version (if applicable): 

----------

## Problem Description

I have set the env variables CLIENT_PROXY_HOST,CLIENT_PROXY_PORT,CLIENT_PROXY_TYPE,CLIENT_PROXY_NO_DASH_PROXY but its not overriding the proxy config in application yml. 

I tried with  below configs but it didnt work
1
client:
  user-agent: "Helidon ai-apps"
  proxy:{}
  relative-uris: true
2
client:
  user-agent: "Helidon ai-apps"
  relative-uris: true

Builder used to create webclient:

jdkTimeout = config.get(JDK_HTTP_CLIENT_TIMEOUT).asInt().get();
        clientBuilder = WebClient.builder().config(config.get(CONFIG_WEBCLIENT))
                .connectTimeout(jdkTimeout, TimeUnit.SECONDS).addService(WebClientTracing.create());

The proxy will work with below application yml configuration

client:
  user-agent: "Helidon ai-apps"
  **proxy:
    host:**
  relative-uris: true

when we have entry for proxy and host like above everything work fine.

problem is easily reproducible

**Comment by Verdent** [comment] 2022-06-30 16:03
I could not reproduce this issue. Could you please share how you create the Config?

**Comment by georgyrajan** [comment] 2022-07-04 02:21
//application.yml
client:
user-agent: "Helidon ai-apps"
proxy:{}
relative-uris: true

@Verdent 
// the class in which client is created and constructor method.
@ApplicationScoped
public class CxService {
  WebClient.Builder clientBuilder;
    WebClient client;
    @Inject
    public CxService(Config config) {
        jdkTimeout = config.get(JDK_HTTP_CLIENT_TIMEOUT).asInt().get();
        clientBuilder = WebClient.builder().config(config.get(CONFIG_WEBCLIENT))
                .connectTimeout(jdkTimeout, TimeUnit.SECONDS).addService(WebClientTracing.create());
    }

// method where client is used

    protected Single<WebClientResponse> updateIncident(IncidentPrediction incident, CxConfig cxConfig,
            ConsulConfidenceScore consulConfidenceScore) {
      
        client = clientBuilder.baseUri(cxConfig.getUrl()).addMediaSupport(JsonpSupport.create())
                .addHeader(Http.Header.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                .addHeader(Http.Header.AUTHORIZATION,
                        getBasicAuth.apply(cxConfig.getUsername(), cxConfig.getPassword()))
                .addHeader(CommonConstants.OSVC_API_CREST_HEADER, OSVC_API_CREST_HEADER_VALUE).build();
        return cxRestClient.doCxRestCallWebclient(incident, json, client);
    }

// method where REST call is made

        @Timed(name = CommonConstants.METRICS_UPDATE_CX_RESPONSE_TIMER, absolute = true)
        @Traced
        public Single<WebClientResponse> doCxRestCallWebclient(IncidentPrediction incident, JsonObject json,
                WebClient client) {
            return Single.create(() -> client.method(Http.Method.PATCH).path(OSVC_INCIDENT_PATH + incident.getId())
                    .submit(json.toString()).await());
        }

**Comment by Verdent** [comment] 2022-09-08 13:04
I see. Well System and Env properties are not meant to create whole new config object, but what you can do, is to set proxy type to NONE in your config:
```yaml
client:
   proxy:
      type: "NONE"
```
and when you use your system properties now, the same way you are using them, everything will work as expected.

Anyway this is not a bug. Closing the issue.

**Closed by Verdent** 2022-09-08 13:04 UTC
