### ISSUE TITLE
AsciiDoctor error for site generation

### ISSUE THREAD

**Issue by NandX00r** [oracle/helidon#3067] opened 2021-06-03 13:35 UTC
## Environment Details

* JDK version: 16
* OS: macos

## Problem Description
1. I pulled the project src code and build it with maven. it compiles.
2. I want to generate the same documentation like [helidon documentation](https://helidon.io/docs/v1/#/about/01_overview)
3. 
$ mvn site
....
...

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.8.2:site (default-site) on project helidon-project: Error generating maven-javadoc-plugin:3.2.0:aggregate-no-fork report: 
[ERROR] Exit code: 1 - warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR]   reason: class file for org.jboss.logging.annotations.Message$Format not found
.....
...

4. what I'm missing, any guidance will be appreciated.

**Comment by romain-grecourt** [comment] 2021-06-03 17:04
Does it work with JDK11 ?

**Comment by barchetta** [comment] 2021-06-03 20:43
I have reproduced with JDK 16. As @romain-grecourt says, this should work with JDK 11 where this error was considered non-fatal by javadoc. Looks like we can fix the  Format.MESSAGE_FORMAT errors by adding the following to the aggregated javadoc config in the root pom.xml (not sure why we need to do this, but javadoc is full of mysteries):

```
                            <additionalDependencies>
                                <additionalDependency>
                                    <groupId>org.jboss.logging</groupId>
                                    <artifactId>jboss-logging-annotations</artifactId>
                                    <version>${version.lib.jboss-logging-annotations}</version>
                                </additionalDependency>
                            </additionalDependencies>
```

Once this is fixed we then get other errors related to javadoc formatting which appears to be stricter in JDK 16.

**Comment by NandX00r** [comment] 2021-06-05 09:14
Thanks @barchetta 

I tried to generate [documentation ](https://helidon.io/docs/v2/#/about/01_overview) and failed.

- MacOs
- JDk11&16:   $ mvn install produce build success
- when I try to execute $ mvn site I get:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.8.2:site (default-site) on project helidon-project: Error generating maven-javadoc-plugin:3.2.0:aggregate-no-fork report: 
[ERROR] Exit code: 1 - warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR]   reason: class file for org.jboss.logging.annotations.Message$Format not found
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/common/http/src/main/java/io/helidon/common/http/Content.java:31: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Default publisher contract</h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/config/config/src/main/java/io/helidon/config/ValueResolvingFilter.java:40: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>How to Activate This Filter</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/config/config/src/main/java/io/helidon/config/spi/PollingStrategy.java:82: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Meta-configuration Support for Custom Polling Strategies</h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/config/config/src/main/java/io/helidon/config/Config.java:41: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>Configuration</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ResponseHeaders.java:39: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Lifecycle</h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/RequestPredicate.java:53: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Examples</h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/PathMatcher.java:27: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3><a id="pattern">Web Server Path Pattern</a></h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:41: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Lifecycle</h3>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/Main.java:29: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>Startup</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/microprofile/cors/src/main/java/io/helidon/microprofile/cors/package-info.java:18: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>Helidon MP CORS Support</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/security/security/src/main/java/io/helidon/security/package-info.java:18: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>Security</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/cors/src/main/java/io/helidon/webserver/cors/package-info.java:19: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
[ERROR]  * <h1>Helidon SE CORS Support</h1>
[ERROR]    ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:117: error: unexpected heading used: <H3>, compared to implicit preceding heading: <H3>
[ERROR]      * <h3>Marshalling</h3>
[ERROR]        ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:129: error: unexpected heading used: <H3>, compared to implicit preceding heading: <H3>
[ERROR]      * <h3>Blocking</h3>
[ERROR]        ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:159: error: unexpected heading used: <H3>, compared to implicit preceding heading: <H3>
[ERROR]      * <h3>Blocking</h3>
[ERROR]        ^
[ERROR] /Users/agerber/Desktop/Amin/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:177: error: unexpected heading used: <H3>, compared to implicit preceding heading: <H3>
[ERROR]      * <h3>Blocking</h3>
[ERROR]        ^
[ERROR] 
[ERROR] Command line was: /Users/agerber/Library/Java/JavaVirtualMachines/openjdk-16.0.1/Contents/Home/bin/javadoc -J-Dhttp.agent=maven-javadoc-plugin --add-exports=java.base/sun.security.util=io.helidon.common.pki @options @argfile
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/agerber/Desktop/Amin/workspace/helidon/target/site/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :helidon-project

---------------

After 24 hours still can't understand what I'm missing.

**Comment by NandX00r** [comment] 2021-06-05 09:32
Thanks @barchetta

I tried to generate documentation and failed.
1. MacOs
2. JDk11&16: $ mvn install produce build success

3. when I try to execute $ mvn site I get:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.8.2:site (default-site) on project helidon-project: Error generating maven-javadoc-plugin:3.2.0:aggregate-no-fork report:
[ERROR] Exit code: 1 - warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] reason: class file for org.jboss.logging.annotations.Message$Format not found
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
....
....
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] warning: unknown enum constant Format.MESSAGE_FORMAT
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/common/http/src/main/java/io/helidon/common/http/Content.java:31: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Default publisher contract

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/config/config/src/main/java/io/helidon/config/ValueResolvingFilter.java:40: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
How to Activate This Filter

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/config/config/src/main/java/io/helidon/config/spi/PollingStrategy.java:82: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Meta-configuration Support for Custom Polling Strategies

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/config/config/src/main/java/io/helidon/config/Config.java:41: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Configuration

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ResponseHeaders.java:39: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Lifecycle

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/RequestPredicate.java:53: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Examples

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/PathMatcher.java:27: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Web Server Path Pattern

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:41: error: heading used out of sequence:
, compared to implicit preceding heading:

[ERROR] *
Lifecycle

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/Main.java:29: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Startup

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/microprofile/cors/src/main/java/io/helidon/microprofile/cors/package-info.java:18: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Helidon MP CORS Support

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/security/security/src/main/java/io/helidon/security/package-info.java:18: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Security

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/cors/src/main/java/io/helidon/webserver/cors/package-info.java:19: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Helidon SE CORS Support

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:117: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Marshalling

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:129: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Blocking

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:159: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Blocking

[ERROR] ^
[ERROR] /Users/[UserName]/Desktop/[Directory]/workspace/helidon/webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java:177: error: unexpected heading used:
, compared to implicit preceding heading:

[ERROR] *
Blocking

[ERROR] ^
[ERROR]
[ERROR] Command line was: /Users/[UserName]/Library/Java/JavaVirtualMachines/openjdk-16.0.1/Contents/Home/bin/javadoc -J-Dhttp.agent=maven-javadoc-plugin --add-exports=java.base/sun.security.util=io.helidon.common.pki @options @argfile
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/Users/[UserName]/Desktop/[Directory]/workspace/helidon/target/site/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :helidon-project
-----------
4. kindly, can you explain to me what I'm missing?

**Comment by barchetta** [comment] 2021-06-18 16:18
Short answer: you need to use Java 11 to build Helidon javadocs.

There looks to be no way to format javadocs to satisfy doclint on both Java 11 and Java 16 because they each enforce some rules differently.  So build the workspace and site using Java 11.

I have fixed the Format.MESSAGE_FORMAT errors since those were showing up with Java 11 as well (#3077).

I have also created an issue (#3078) for cleaning up doclint warnings under Java 11.

Therefore I am closing this issue since we won't be doing anything to get the javadocs to build with Java 16.

**Closed by barchetta** 2021-06-18 16:18 UTC
Labels: P4, docs
