### ISSUE TITLE
Jib created Microprofile image cannot resolve CDI classes

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#419] opened 2019-02-18 16:27 UTC
## Environment Details
* Helidon Version: `1.0.0`
* Helidon SE or Helidon MP: `MP`
* JDK version: `openjdk:8-alpine` and `gcr.io/distroless/java`
* OS: ^
* Docker version (if applicable): Docker Desktop 2.0.0.2 using Jib 1.0.0 created image

----------

## Problem Description
No CDI classes are being introspected by Weld so no JAX-RS resources are available resulting in 404 Not Found. The `beans.xml` files are being found:

```
Feb 18, 2019 3:24:09 PM org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner getBeanArchiveReference
DEBUG: Resolved bean archive reference: /app/resources for URL: file:/app/resources/META-INF/beans.xml
```
But later down I get:

```
Feb 18, 2019 3:25:33 PM io.helidon.microprofile.server.Server$Builder resourcesFromContainer
WARNING: Failed to find JAX-RS resource to use
```

I've remotely debugged the image an no classes are being passed to `io.helidon.microprofile.server.ServerCdiExtension#gatherApplications(...)` so not being initialised. 

This is also confirmed by no message from Weld when processing the classes as it _should_ say something like:

```
Feb 18, 2019 4:16:14 PM org.jboss.weld.bootstrap.events.ContainerLifecycleEvents fireProcessAnnotatedType
TRACE: Sending PAT using the fast event resolver: [BackedAnnotatedType] public @ApplicationPath @LoginConfig @ApplicationScoped class foo.MyApplication
```

My assumption is Helidon Microprofile really doesn't like processing the `/app/classes/*` when running via Docker.

This works locally using `io.helidon.microprofile.server.Main`, the issue is reproducible every time.

## Steps to reproduce

1. Create simple Microprofile 1.2 project
2. Add `javax.ws.rs.core.Application` implementation with `@javax.ws.rs.ApplicationPath` and `@javax.enterprise.context.ApplicationScoped`
3. Build Docker image using Jib 1.0.0 as per [instructions](https://helidon.io/docs/latest/#/guides/05_Dockerfile),
4. Run in docker and try and hit endpoints.

Unfortunately, I can't provide an example project yet.

**Comment by dansiviter** [comment] 2019-02-18 17:38
Found the problem: Weld expects the `bean.xml` to be in the same classpath as the classes. Ordinarily in an IDE or via Maven `/target/classes` this would be the case so no problem with Weld. Unfortunately, Jib creates separate directories for resources and classes and attaches them separately to the classpath:

```
/app
  - /classes
    - /foo
      - MyWeldManagedBean.class
  - /resources
    - /META-INF
      - beans.xml   #  Weld can't find MyWeldManagedBean as this is separate
```

Workaround is to put `beans.xml` into `/src/main/jib/app/classes` as it then placed it into the right place.

Arguably this is a problem with Jib: GoogleContainerTools/jib#1488

**Comment by spericas** [comment] 2019-02-19 15:15
@dansiviter I guess when you say "same classpath" you mean "same classpath entry", correct? I seem to recall people having problems with Gradle and other tools because of this. I don't know if there's a way around it using Weld; I suspect the rationale for this is to support bean and non-bean archives in the same classpath. Do we need to keep this issue open?

**Comment by dansiviter** [comment] 2019-02-19 21:06
Yea, 'classpath entry' is more accurate. This issue will affect all Helidon MP using Jib so not sure if this should be documented so others don't get caught out by it?

**Comment by ljnelson** [comment] 2019-02-22 04:15
I support the interpretation That says this is a Jib issue; `META-INF/beans.xml` resources identify CDI bean archives that by definition must be rooted at the same location.

**Comment by tomas-langer** [comment] 2019-04-16 20:39
As mentioned above, this is caused by JIB's handling of class path.
See https://github.com/GoogleContainerTools/jib/issues/1488 for more details.
Closing as there is nothing we can do in Helidon.
Workaround as described in the JIB case:
Place `beans.xml` file in `src/main/jib/app/classes/META-INF`.

**Closed by tomas-langer** 2019-04-16 20:39 UTC
Labels: MP
